let youFirstName = "Mykhaylo";
let youLastName = "Tlumak";
let youGroup = "JS for QC 2021";
let youOld = 50;
let youMarried = true;
console.log(typeof youFirstName);
console.log(typeof youLastName);
console.log(typeof youGroup);
console.log(typeof youOld);
console.log(typeof youMarried);
console.log(youOld, youMarried, youFirstName, youLastName, youGroup);
let youNull= null;
let youUndefined;
console.log(youNull, youUndefined);